---
title: "Exercises in quarto"
author: "Jakob Skou Pedersen and Simon Grund Sørensen"
date: "`r Sys.Date()`"
format: html
---

```{r}
#| label: setup
#| include: false
library(tidyverse)
library(knitr)
knitr::opts_chunk$set(echo = TRUE)
```

## Quarto exercises part I

Remember to refer to the **Quarto** cheat sheet and the [**Quarto guide**](https://quarto.org/docs/guide/) when solving the below.

1. Render this document 
2. Return here to Posit (R-studio) and make a new Quarto document with html output
3. Edit the document, by removing the pre-made text and make a new text with the following:
    - headers of different levels.
    - text typeset in *italic* and **bold**.
    - ordered and unordered lists.
    - a hyperlink
4. Try to render your document.
5. Change output to pdf and render it again (might not work without additional software installed).
6. Change output to docx and render it again.
7. Add an R code chunk.
8. Try making a plot based on the mpg data set.
    - render the document.
9. Try adding the chd_500 data set and make a plot based on it.
    - Use *read_rds("chd_500.rds")* to load it from file.

## Quarto exercises part II

1. Make a simple table by hand
2. Make kable table with the first 10 lines of the chd_500 data set (Hint: use ?kable to get help. Remember to load the kable package before using it in your script). 
    - Remove variables if tables becomes too wide to fit.
3. Make a mermaid (or graphviz) [diagram](https://quarto.org/docs/authoring/diagrams.html) with boxes representing, e.g., your genealogy.
4. Add a table of contents by modifying the YAML header (see the cheat sheet).
5. If time permits:
    - write some inline R code.
    - add some formulas using latex (see the uploaded latexCheatSheet.pdf).
  
  

